### ISSUE TITLE
Please link to the appropriate FreeCAD forum thread in README.md so users have context

### ISSUE THREAD

**Issue by luzpaz** [CyrilWaechter/freecad-stubs#1]
Thanks!

**Comment by CyrilWaechter** [comment]
What is your definition of appropriate ? One of the following ?
* [Type-checked Python](https://forum.freecadweb.org/viewtopic.php?t=49917)
* [Please demonstrate using a remote text editor to substitute the Python editor in FreeCAD](https://forum.freecadweb.org/viewtopic.php?f=8&t=40673)

**Comment by luzpaz** [comment]
Both is cool :sunglasses:
